import ArrowheadPlugin from "../main";

export interface Post {
  title: string;
  url: string;
  date: string;
  tags: string[];
  excerpt: string;
}

export interface TemplateData {
  title: string;
  content: string;
  description?: string;
  tags?: string[];
  date?: string;
  lastModified?: string;
  author?: string;
  categories?: string[];
  siteTitle?: string;
  siteDescription?: string;
  posts?: Post[];
  allPages?: { title: string; url: string; length?: number }[];
  [key: string]: unknown;
}

export class TemplateEngine {
  private plugin: ArrowheadPlugin;
  private cachedTemplate: string | null = null;
  private currentTemplateName: string | null = null;

  constructor(plugin: ArrowheadPlugin) {
    this.plugin = plugin;
  }

  async render(template: string, data: TemplateData): Promise<string> {
    let rendered = template;
    
    rendered = await this.renderPartials(rendered);
    rendered = this.renderLoops(rendered, data);
    rendered = this.renderConditionals(rendered, data);
    rendered = this.renderPlaceholders(rendered, data);
    
    return rendered;
  }

  private renderPartials(template: string): Promise<string> {
    const partialRegex = /\{\{>\s*(\w+)\s*\}\}/g;
    const partialsToLoad: string[] = [];
    let match;
    
    while ((match = partialRegex.exec(template)) !== null) {
      const partialName = match[1];
      if (partialName && !partialsToLoad.includes(partialName)) {
        partialsToLoad.push(partialName);
      }
    }
    
    return (async () => {
      const loadedPartials: Record<string, string> = {};
      for (const partialName of partialsToLoad) {
        loadedPartials[partialName] = await this.loadPartial(partialName);
      }
      
      return template.replace(partialRegex, (match, partialName) => {
        return loadedPartials[partialName || ""] || match;
      });
    })();
  }

  private async loadPartial(partialName: string): Promise<string> {
    const templateName = this.currentTemplateName || "default";
    const partialPath = `templates/${templateName}/partials/${partialName}.html`;
    
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath(partialPath);
      if (file) {
        return await this.plugin.app.vault.cachedRead(file as any);
      }
    } catch (error) {
      console.warn(`Custom partial not found: ${partialPath}`);
    }
    
    return this.getDefaultPartial(partialName);
  }

  private getDefaultPartial(partialName: string): string {
    const partials: Record<string, string> = {
      header: `<header class="site-header">
  <nav class="site-nav">
    <a href="/" class="site-title">{{siteTitle}}</a>
    <ul class="nav-links">
      <li><a href="/">Home</a></li>
      <li><a href="/sitemap">Sitemap</a></li>
    </ul>
  </nav>
</header>`,
      footer: `<footer class="site-footer">
  <p>Generated by <a href="https://github.com/yourusername/arrowhead-obsidian-plugin">Arrowhead</a></p>
  {{#if lastModified}}
  <p>Last updated: {{lastModified}}</p>
  {{/if}}
</footer>`
    };
    
    return partials[partialName] || "";
  }

  private renderPlaceholders(template: string, data: TemplateData): string {
    return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
      if (key in data) {
        return String(data[key]);
      }
      return match;
    });
  }

  private renderConditionals(template: string, data: TemplateData): string {
    let result = template;
    
    const ifRegex = /\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g;
    result = result.replace(ifRegex, (match, key, content) => {
      const value = data[key];
      if (value) {
        return content;
      }
      return "";
    });
    
    return result;
  }

  private getValue(key: string, data: TemplateData): unknown {
    return data[key];
  }

  private renderLoops(template: string, data: TemplateData): string {
    const loopRegex = /\{\{#each\s+(\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g;
    
    return template.replace(loopRegex, (match, key, content) => {
      if (Array.isArray(data[key])) {
        return (data[key] as unknown[]).map((item, index) => {
          let itemContent = content;
          
          if (typeof item === "object" && item !== null) {
            const itemObj = item as Record<string, unknown>;
            itemContent = itemContent.replace(/\{\{(\w+)\}\}/g, (_match: string, propKey: string) => {
              return String(itemObj[propKey] ?? "");
            });
          }
          
          itemContent = itemContent.replace(/\{\{@index\}\}/g, String(index));
          itemContent = itemContent.replace(/\{\{@first\}\}/g, index === 0 ? "true" : "");
          itemContent = itemContent.replace(/\{\{@last\}\}/g, index === (data[key] as unknown[]).length - 1 ? "true" : "");
          
          itemContent = itemContent.replace(/\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g, (ifMatch: string, ifKey: string, ifContent: string) => {
            if (typeof item === "object" && item !== null) {
              const itemObj = item as Record<string, unknown>;
              if (itemObj[ifKey]) {
                return ifContent;
              }
            }
            return "";
          });
          
          return itemContent;
        }).join("");
      }
      return "";
    });
  }

  async loadTemplate(templateName: string): Promise<string> {
    if (this.cachedTemplate && this.currentTemplateName === templateName) {
      return this.cachedTemplate;
    }
    
    let template: string;
    
    if (templateName === "default") {
      template = this.getDefaultTemplate();
    } else if (templateName === "minimal") {
      template = this.getMinimalTemplate();
    } else if (templateName === "notebook") {
      template = this.getNotebookTemplate();
    } else {
      const templatePath = `templates/${templateName}/layout.html`;
      try {
        const file = this.plugin.app.vault.getAbstractFileByPath(templatePath);
        if (file) {
          template = await this.plugin.app.vault.cachedRead(file as any);
        } else {
          console.warn(`Custom template not found: ${templateName}`);
          template = this.getDefaultTemplate();
        }
      } catch {
        console.warn(`Custom template not found: ${templateName}`);
        template = this.getDefaultTemplate();
      }
    }
    
    this.cachedTemplate = template;
    this.currentTemplateName = templateName;
    
    return template;
  }

  getCachedTemplate(): string | null {
    return this.cachedTemplate;
  }

  private getDefaultTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <meta name="generator" content="Arrowhead Static Site Generator">
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/styles.css">
</head>
<body>
  <header class="site-header">
    <nav class="site-nav">
      <a href="/" class="site-title">{{siteTitle}}</a>
      <ul class="nav-links">
        <li><a href="/">Home</a></li>
        <li><a href="/sitemap">Sitemap</a></li>
      </ul>
    </nav>
  </header>
  
  <main class="site-content">
    {{content}}
  </main>
  
  <footer class="site-footer">
    <p>Generated by <a href="https://github.com/yourusername/arrowhead-obsidian-plugin">Arrowhead</a></p>
    {{#if lastModified}}
    <p>Last updated: {{lastModified}}</p>
    {{/if}}
  </footer>
</body>
</html>`;
  }

  private getMinimalTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/minimal.css">
</head>
<body>
  <main class="content">
    <article>
      {{content}}
    </article>
  </main>
</body>
</html>`;
  }

  private getNotebookTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}}</title>
  <link rel="stylesheet" href="/assets/notebook.css">
</head>
<body>
  <div class="notebook-container">
    <aside class="notebook-sidebar">
      <h2>{{siteTitle}}</h2>
      <nav>
        <a href="/">Home</a>
        <a href="/sitemap">All Pages</a>
      </nav>
    </aside>
    
    <main class="notebook-content">
      <header class="notebook-header">
        <h1>{{title}}</h1>
        {{#if lastModified}}
        <time>{{lastModified}}</time>
        {{/if}}
      </header>
      
      <div class="notebook-body">
        {{content}}
      </div>
    </main>
  </div>
</body>
</html>`;
  }
}