import ArrowheadPlugin from "../main";

export interface TemplateData {
  title: string;
  content: string;
  description?: string;
  tags?: string[];
  date?: string;
  lastModified?: string;
  author?: string;
  categories?: string[];
  [key: string]: unknown;
}

export class TemplateEngine {
  private plugin: ArrowheadPlugin;

  constructor(plugin: ArrowheadPlugin) {
    this.plugin = plugin;
  }

  render(template: string, data: TemplateData): string {
    let rendered = template;
    
    rendered = this.renderPlaceholders(rendered, data);
    rendered = this.renderConditionals(rendered, data);
    rendered = this.renderLoops(rendered, data);
    
    return rendered;
  }

  private renderPlaceholders(template: string, data: TemplateData): string {
    return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
      if (key in data) {
        return String(data[key]);
      }
      return match;
    });
  }

  private renderConditionals(template: string, data: TemplateData): string {
    const ifRegex = /\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g;
    
    return template.replace(ifRegex, (match, key, content) => {
      if (data[key]) {
        return content;
      }
      return "";
    });
  }

  private renderLoops(template: string, data: TemplateData): string {
    const loopRegex = /\{\{#each\s+(\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g;
    
    return template.replace(loopRegex, (match, key, content) => {
      if (Array.isArray(data[key])) {
        return (data[key] as unknown[]).map((item, index) => {
          let itemContent = content;
          
          if (typeof item === "object" && item !== null) {
            itemContent = itemContent.replace(/\{\{(\w+)\}\}/g, (_match: string, propKey: string) => {
              return String((item as Record<string, unknown>)[propKey] ?? "");
            });
          }
          
          itemContent = itemContent.replace(/\{\{@index\}\}/g, String(index));
          itemContent = itemContent.replace(/\{\{@first\}\}/g, index === 0 ? "true" : "");
          itemContent = itemContent.replace(/\{\{@last\}\}/g, index === (data[key] as unknown[]).length - 1 ? "true" : "");
          
          return itemContent;
        }).join("");
      }
      return "";
    });
  }

  async loadTemplate(templateName: string): Promise<string> {
    if (templateName === "default") {
      return this.getDefaultTemplate();
    }
    
    if (templateName === "minimal") {
      return this.getMinimalTemplate();
    }
    
    if (templateName === "notebook") {
      return this.getNotebookTemplate();
    }
    
    const templatePath = `templates/${templateName}/layout.html`;
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath(templatePath);
      if (file) {
        return await this.plugin.app.vault.cachedRead(file as any);
      }
    } catch {
      console.warn(`Custom template not found: ${templateName}`);
    }
    
    return this.getDefaultTemplate();
  }

  private getDefaultTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <meta name="generator" content="Arrowhead Static Site Generator">
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/styles.css">
</head>
<body>
  <header class="site-header">
    <nav class="site-nav">
      <a href="/" class="site-title">{{siteTitle}}</a>
      <ul class="nav-links">
        <li><a href="/">Home</a></li>
        <li><a href="/sitemap">Sitemap</a></li>
      </ul>
    </nav>
  </header>
  
  <main class="site-content">
    {{content}}
  </main>
  
  <footer class="site-footer">
    <p>Generated by <a href="https://github.com/yourusername/arrowhead-obsidian-plugin">Arrowhead</a></p>
    {{#if lastModified}}
    <p>Last updated: {{lastModified}}</p>
    {{/if}}
  </footer>
</body>
</html>`;
  }

  private getMinimalTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/minimal.css">
</head>
<body>
  <main class="content">
    <article>
      {{content}}
    </article>
  </main>
</body>
</html>`;
  }

  private getNotebookTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}}</title>
  <link rel="stylesheet" href="/assets/notebook.css">
</head>
<body>
  <div class="notebook-container">
    <aside class="notebook-sidebar">
      <h2>{{siteTitle}}</h2>
      <nav>
        <a href="/">Home</a>
        <a href="/sitemap">All Pages</a>
      </nav>
    </aside>
    
    <main class="notebook-content">
      <header class="notebook-header">
        <h1>{{title}}</h1>
        {{#if lastModified}}
        <time>{{lastModified}}</time>
        {{/if}}
      </header>
      
      <div class="notebook-body">
        {{content}}
      </div>
    </main>
  </div>
</body>
</html>`;
  }
}