import ArrowheadPlugin from "../main";

export interface Post {
  title: string;
  url: string;
  date: string;
  tags: string[];
  excerpt: string;
}

export interface TemplateData {
  title: string;
  content: string;
  description?: string;
  tags?: string[];
  date?: string;
  lastModified?: string;
  author?: string;
  categories?: string[];
  siteTitle?: string;
  siteDescription?: string;
  posts?: Post[];
  pages?: { title: string; url: string; length?: number }[];
  allPages?: { title: string; url: string; length?: number }[];
  [key: string]: unknown;
}

export class TemplateEngine {
  private plugin: ArrowheadPlugin;
  private cachedTemplate: string | null = null;
  private currentTemplateName: string | null = null;

  constructor(plugin: ArrowheadPlugin) {
    this.plugin = plugin;
  }

  async render(template: string, data: TemplateData): Promise<string> {
    let rendered = template;
    
    rendered = await this.renderPartials(rendered);
    rendered = this.renderLoops(rendered, data);
    rendered = this.renderConditionals(rendered, data);
    rendered = this.renderPlaceholders(rendered, data);
    
    return rendered;
  }

  private renderPartials(template: string): Promise<string> {
    const partialRegex = /\{\{>\s*(\w+)\s*\}\}/g;
    const partialsToLoad: string[] = [];
    let match;
    
    while ((match = partialRegex.exec(template)) !== null) {
      const partialName = match[1];
      if (partialName && !partialsToLoad.includes(partialName)) {
        partialsToLoad.push(partialName);
      }
    }
    
    return (async () => {
      const loadedPartials: Record<string, string> = {};
      for (const partialName of partialsToLoad) {
        loadedPartials[partialName] = await this.loadPartial(partialName);
      }
      
      return template.replace(partialRegex, (match, partialName) => {
        return loadedPartials[partialName || ""] || match;
      });
    })();
  }

  private async loadPartial(partialName: string): Promise<string> {
    const templateName = this.currentTemplateName || "default";
    const partialPath = `templates/${templateName}/partials/${partialName}.html`;
    
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath(partialPath);
      if (file) {
        return await this.plugin.app.vault.cachedRead(file as any);
      }
    } catch (error) {
      console.warn(`Custom partial not found: ${partialPath}`);
    }
    
    return this.getDefaultPartial(partialName);
  }

  private getDefaultPartial(partialName: string): string {
    const partials: Record<string, string> = {
      header: `<header class="site-header">
  <nav class="site-nav">
    <a href="/" class="site-title">{{siteTitle}}</a>
    <ul class="nav-links">
      <li><a href="/">Home</a></li>
    </ul>
  </nav>
</header>`,
      footer: `<footer class="site-footer">
  <p>Generated by <a href="https://github.com/yourusername/arrowhead-obsidian-plugin">Arrowhead</a></p>
  {{#if lastModified}}
  <p>Last updated: {{lastModified}}</p>
  {{/if}}
</footer>`
    };
    
    return partials[partialName] || "";
  }

  private renderPlaceholders(template: string, data: TemplateData): string {
    return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
      if (key in data) {
        return String(data[key]);
      }
      return match;
    });
  }

  private renderConditionals(template: string, data: TemplateData): string {
    let result = template;
    
    const ifRegex = /\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g;
    result = result.replace(ifRegex, (match, key, content) => {
      const value = data[key];
      if (value) {
        return content;
      }
      return "";
    });
    
    return result;
  }

  private getValue(key: string, data: TemplateData): unknown {
    return data[key];
  }

  private renderLoops(template: string, data: TemplateData): string {
    const loopRegex = /\{\{#each\s+(\w+)\}\}([\s\S]*?)\{\{\/each\}\}/g;
    
    return template.replace(loopRegex, (match, key, content) => {
      if (Array.isArray(data[key])) {
        return (data[key] as unknown[]).map((item, index) => {
          let itemContent = content;
          
          if (typeof item === "object" && item !== null) {
            const itemObj = item as Record<string, unknown>;
            itemContent = itemContent.replace(/\{\{(\w+)\}\}/g, (_match: string, propKey: string) => {
              return String(itemObj[propKey] ?? "");
            });
          }
          
          itemContent = itemContent.replace(/\{\{@index\}\}/g, String(index));
          itemContent = itemContent.replace(/\{\{@first\}\}/g, index === 0 ? "true" : "");
          itemContent = itemContent.replace(/\{\{@last\}\}/g, index === (data[key] as unknown[]).length - 1 ? "true" : "");
          
          itemContent = itemContent.replace(/\{\{#if\s+(\w+)\}\}([\s\S]*?)\{\{\/if\}\}/g, (ifMatch: string, ifKey: string, ifContent: string) => {
            if (typeof item === "object" && item !== null) {
              const itemObj = item as Record<string, unknown>;
              if (itemObj[ifKey]) {
                return ifContent;
              }
            }
            return "";
          });
          
          return itemContent;
        }).join("");
      }
      return "";
    });
  }

  async loadTemplate(templateName: string): Promise<string> {
    if (this.cachedTemplate && this.currentTemplateName === templateName) {
      return this.cachedTemplate;
    }
    
    let template: string;
    
    if (templateName === "default") {
      template = this.getDefaultTemplate();
    } else if (templateName === "minimal") {
      template = this.getMinimalTemplate();
    } else if (templateName === "notebook") {
      template = this.getNotebookTemplate();
    } else {
      const templatePath = `templates/${templateName}/layout.html`;
      try {
        const file = this.plugin.app.vault.getAbstractFileByPath(templatePath);
        if (file) {
          template = await this.plugin.app.vault.cachedRead(file as any);
        } else {
          console.warn(`Custom template not found: ${templateName}`);
          template = this.getDefaultTemplate();
        }
      } catch {
        console.warn(`Custom template not found: ${templateName}`);
        template = this.getDefaultTemplate();
      }
    }
    
    this.cachedTemplate = template;
    this.currentTemplateName = templateName;
    
    return template;
  }

  getCachedTemplate(): string | null {
    return this.cachedTemplate;
  }

  private getDefaultTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <meta name="generator" content="Arrowhead Static Site Generator">
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/styles.css">
</head>
<body>
  <header class="site-header">
    <nav class="site-nav">
      <a href="/" class="site-title">{{siteTitle}}</a>
      <ul class="nav-links">
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
  </header>
  
  <main class="site-content">
    {{content}}
  </main>
  
  <footer class="site-footer">
    <p>Generated by <a href="https://github.com/yourusername/arrowhead-obsidian-plugin">Arrowhead</a></p>
    {{#if lastModified}}
    <p>Last updated: {{lastModified}}</p>
    {{/if}}
  </footer>
</body>
</html>`;
  }

  private getMinimalTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}} | {{siteTitle}}</title>
  <link rel="stylesheet" href="/assets/minimal.css">
</head>
<body>
  <main class="content">
    <article>
      {{content}}
    </article>
  </main>
</body>
</html>`;
  }

  private getNotebookTemplate(): string {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {{#if description}}
  <meta name="description" content="{{description}}">
  {{/if}}
  <title>{{title}}</title>
  <link rel="stylesheet" href="/assets/notebook.css">
</head>
<body>
  <div class="notebook-container">
    <aside class="notebook-sidebar">
      <h2>{{siteTitle}}</h2>
      <nav>
        <a href="/">Home</a>
      </nav>
    </aside>
    
    <main class="notebook-content">
      <header class="notebook-header">
        <h1>{{title}}</h1>
        {{#if lastModified}}
        <time>{{lastModified}}</time>
        {{/if}}
      </header>
      
      <div class="notebook-body">
        {{content}}
      </div>
    </main>
  </div>
</body>
</html>`;
  }

  getDefaultCss(): string {
    return `:root {
  --font-body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, sans-serif;
  --font-mono: "SF Mono", "Fira Code", Consolas, monospace;
  --color-primary: #5c6bc0;
  --color-primary-dark: #3f51b5;
  --color-text: #2c3e50;
  --color-text-light: #636e72;
  --color-bg: #ffffff;
  --color-bg-secondary: #f8f9fa;
  --color-border: #e0e0e0;
  --max-width: 900px;
  --spacing-unit: 1rem;
  --border-radius: 8px;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: var(--font-body);
  font-size: 16px;
  line-height: 1.6;
  color: var(--color-text);
  background-color: var(--color-bg);
}

h1, h2, h3, h4, h5, h6 {
  color: var(--color-text);
  margin-bottom: var(--spacing-unit);
  line-height: 1.3;
}

h1 { font-size: 2.25rem; }
h2 { font-size: 1.75rem; }
h3 { font-size: 1.5rem; }
h4 { font-size: 1.25rem; }

a {
  color: var(--color-primary);
  text-decoration: none;
  transition: color 0.2s ease;
}

a:hover {
  color: var(--color-primary-dark);
  text-decoration: underline;
}

p {
  margin-bottom: var(--spacing-unit);
}

code {
  font-family: var(--font-mono);
  font-size: 0.9em;
  background: var(--color-bg-secondary);
  padding: 0.2em 0.4em;
  border-radius: 4px;
}

pre {
  background: var(--color-bg-secondary);
  padding: var(--spacing-unit);
  border-radius: var(--border-radius);
  overflow-x: auto;
  margin-bottom: var(--spacing-unit);
}

pre code {
  background: transparent;
  padding: 0;
}

blockquote {
  border-left: 4px solid var(--color-primary);
  padding-left: var(--spacing-unit);
  margin: var(--spacing-unit) 0;
  color: var(--color-text-light);
  font-style: italic;
}

ul, ol {
  margin-bottom: var(--spacing-unit);
  padding-left: 1.5rem;
}

li {
  margin-bottom: 0.5rem;
}

img {
  max-width: 100%;
  height: auto;
  border-radius: var(--border-radius);
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: var(--spacing-unit);
}

th, td {
  border: 1px solid var(--color-border);
  padding: 0.75rem;
  text-align: left;
}

th {
  background: var(--color-bg-secondary);
  font-weight: 600;
}

hr {
  border: none;
  border-top: 1px solid var(--color-border);
  margin: calc(var(--spacing-unit) * 2) 0;
}

.site-header {
  background: var(--color-bg-secondary);
  border-bottom: 1px solid var(--color-border);
  padding: var(--spacing-unit);
  position: sticky;
  top: 0;
  z-index: 100;
}

.site-nav {
  max-width: var(--max-width);
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.site-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--color-text);
}

.nav-links {
  display: flex;
  list-style: none;
  gap: 1.5rem;
  margin: 0;
  padding: 0;
}

.nav-links a {
  color: var(--color-text);
  font-weight: 500;
}

.nav-links a:hover {
  color: var(--color-primary);
  text-decoration: none;
}

.site-content {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: calc(var(--spacing-unit) * 2) var(--spacing-unit);
}

.site-content h1 {
  margin-top: 0;
}

.site-footer {
  background: var(--color-bg-secondary);
  border-top: 1px solid var(--color-border);
  padding: calc(var(--spacing-unit) * 2) var(--spacing-unit);
  text-align: center;
  color: var(--color-text-light);
  font-size: 0.9rem;
}

.footer-content {
  max-width: var(--max-width);
  margin: 0 auto;
}

.footer-content a {
  color: var(--color-primary);
}

.sitemap-link {
  display: inline-block;
  margin-top: 0.5rem;
}

.hero {
  background: var(--color-bg-secondary);
  padding: calc(var(--spacing-unit) * 4) var(--spacing-unit);
  text-align: center;
  border-bottom: 1px solid var(--color-border);
}

.hero-content {
  max-width: var(--max-width);
  margin: 0 auto;
}

.hero h1 {
  margin-bottom: var(--spacing-unit);
}

.hero-description {
  font-size: 1.2rem;
  color: var(--color-text-light);
  max-width: 600px;
  margin: 0 auto;
}

.posts-section {
  margin-bottom: calc(var(--spacing-unit) * 3);
}

.posts-section h2 {
  margin-bottom: calc(var(--spacing-unit) * 1.5);
}

.posts-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: var(--spacing-unit);
}

.post-card {
  border: 1px solid var(--color-border);
  border-radius: var(--border-radius);
  padding: var(--spacing-unit);
  transition: box-shadow 0.2s ease, transform 0.2s ease;
}

.post-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.post-card-link {
  display: block;
  color: var(--color-text);
  text-decoration: none;
}

.post-card-link:hover {
  text-decoration: none;
}

.post-card-title {
  font-size: 1.25rem;
  margin-bottom: 0.5rem;
  color: var(--color-primary);
}

.post-card-date {
  display: block;
  font-size: 0.85rem;
  color: var(--color-text-light);
  margin-bottom: 0.5rem;
}

.post-card-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem;
  margin-bottom: 0.5rem;
}

.post-card-tags .tag {
  font-size: 0.75rem;
  padding: 0.15rem 0.4rem;
  background: var(--color-bg-secondary);
  border-radius: 4px;
  color: var(--color-text-light);
}

.post-card-excerpt {
  font-size: 0.9rem;
  color: var(--color-text);
  margin: 0;
  line-height: 1.5;
}

.page-list {
  list-style: none;
  padding: 0;
}

.page-list li {
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--color-border);
}

.page-list a {
  font-size: 1.1rem;
}

.image-embed {
  margin: var(--spacing-unit) 0;
  text-align: center;
}

.image-embed img {
  max-width: 100%;
  border-radius: var(--border-radius);
}

.note-embed {
  background: var(--color-bg-secondary);
  border: 1px solid var(--color-border);
  border-radius: var(--border-radius);
  padding: var(--spacing-unit);
  margin: var(--spacing-unit) 0;
}

.embed-caption {
  color: var(--color-text-light);
  font-size: 0.9rem;
  margin: 0;
  text-align: center;
}

.audio-embed, .video-embed {
  margin: var(--spacing-unit) 0;
  padding: var(--spacing-unit);
  background: var(--color-bg-secondary);
  border-radius: var(--border-radius);
}

.audio-embed p, .video-embed p {
  margin-bottom: 0.5rem;
  color: var(--color-text-light);
}

audio, video {
  width: 100%;
  border-radius: 4px;
}

@media (max-width: 768px) {
  .site-nav {
    flex-direction: column;
    gap: 1rem;
  }
  
  .nav-links {
    gap: 1rem;
  }
  
  h1 { font-size: 1.75rem; }
  h2 { font-size: 1.5rem; }
  h3 { font-size: 1.25rem; }

  .posts-grid {
    grid-template-columns: 1fr;
  }
}`;
  }
}