#!/usr/bin/env node

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');

const FORGEJO_API_URL = process.env.FORGEJO_API_URL || 'https://github.com';
const REPO_OWNER = process.env.FORGEJO_REPO_OWNER || '';
const REPO_NAME = process.env.FORGEJO_REPO_NAME || '';
const TOKEN = process.env.FORGEJO_TOKEN || '';

if (!TOKEN || !REPO_OWNER || !REPO_NAME) {
  console.error('Error: Missing required environment variables');
  console.error('Please set:');
  console.error('  FORGEJO_API_URL (e.g., https://codeberg.org)');
  console.error('  FORGEJO_REPO_OWNER (e.g., greenkey)');
  console.error('  FORGEJO_REPO_NAME (e.g., arrowhead)');
  console.error('  FORGEJO_TOKEN (your Codeberg access token)');
  process.exit(1);
}

const repoPath = `${REPO_OWNER}/${REPO_NAME}`;
const releaseZipPath = join(projectRoot, 'release.zip');

async function createForgejoRelease() {
  console.log('🚀 Creating Forgejo release...\n');

  const manifest = JSON.parse(readFileSync(join(projectRoot, 'manifest.json'), 'utf-8'));
  const version = manifest.version;

  console.log(`📦 Version: ${version}`);
  console.log(`📁 Repository: ${repoPath}`);
  console.log(`🔗 API URL: ${FORGEJO_API_URL}\n`);

  console.log('🔨 Building plugin...');
  try {
    execSync('npm run build', { cwd: projectRoot, stdio: 'inherit' });
    console.log('✅ Build successful\n');
  } catch (error) {
    console.error('❌ Build failed');
    process.exit(1);
  }

  console.log('📦 Creating release package...');
  try {
    execSync(`cd ${projectRoot} && zip -r release.zip main.js manifest.json styles.css`, { 
      stdio: 'inherit' 
    });
    console.log('✅ Release package created\n');
  } catch (error) {
    console.error('❌ Failed to create release package');
    process.exit(1);
  }

  console.log('📤 Uploading release to Codeberg...');

  const createReleaseUrl = `${FORGEJO_API_URL}/api/v1/repos/${repoPath}/releases`;
  
  const releaseData = {
    tag_name: `v${version}`,
    name: `Release v${version}`,
    body: `Release v${version} of Arrowhead Obsidian Plugin\n\nAutomated release generated by Forgejo Actions CI/CD pipeline.`,
    draft: false,
    prerelease: false
  };

  try {
    const createResponse = await fetch(createReleaseUrl, {
      method: 'POST',
      headers: {
        'Authorization': `token ${TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(releaseData)
    });

    if (!createResponse.ok) {
      const errorText = await createResponse.text();
      console.error(`❌ Failed to create release: ${createResponse.status} - ${errorText}`);
      process.exit(1);
    }

    const release = await createResponse.json();
    console.log('✅ Release created successfully!');

    const uploadUrl = `${createReleaseUrl}/${release.id}/assets?name=release.zip`;
    const fileData = readFileSync(releaseZipPath);

    const uploadResponse = await fetch(uploadUrl, {
      method: 'POST',
      headers: {
        'Authorization': `token ${TOKEN}`,
        'Content-Type': 'application/zip'
      },
      body: fileData
    });

    if (!uploadResponse.ok) {
      const errorText = await uploadResponse.text();
      console.error(`⚠️  Release created but failed to upload asset: ${uploadResponse.status} - ${errorText}`);
      console.log(`\n📝 Manual upload required:`);
      console.log(`   1. Go to ${FORGEJO_API_URL}/${repoPath}/-/releases`);
      console.log(`   2. Edit release v${version}`);
      console.log(`   3. Upload release.zip manually`);
    } else {
      console.log('✅ Release asset uploaded successfully!\n');
    }

    console.log(`🎉 Release v${version} is now available!`);
    console.log(`🔗 Download URL: ${FORGEJO_API_URL}/${repoPath}/-/releases/${release.id}/downloads/release.zip`);

  } catch (error) {
    console.error('❌ Failed to upload release:', error.message);
    console.log(`\n📝 Manual upload required:`);
    console.log(`   1. Go to ${FORGEJO_API_URL}/${repoPath}/-/releases`);
    console.log(`   2. Upload release.zip manually`);
    process.exit(1);
  }
}

createForgejoRelease().catch(console.error);